@startuml

class Etapa {
        - maximo : Int
        - personas : Int

        + maximo( unMaximoPasajero : Int): Etapa
        
        + cargarCantidadPasajeros( cantidad : Int)
        
}

class Remolque {
        tipo( e : Etapa) : Remolque

        + cargarCantidadPasajeros( c : Int)
        + cantidadPasajeros() : Int
}

class NoPuedeCargarPasajeros {}

class Error {}

Remolque *- Etapa

Etapa .right.> NoPuedeCargarPasajeros: <<instanciate>>

Error <|-- NoPuedeCargarPasajeros


@enduml
