@startuml

title Un remolque carga 2 personas en fase normal la cantidad de personas es 2

actor User

User -> Etapa **: maximo(2)
return etapa
User -> Remolque **: crear( etapa )
User -> Remolque: cargarCantidadPasajeros(2)
Remolque -> Etapa: cargarCantidadPasajeros(2)
User -> Remolque: cantidadPasajeros()
return 2

@enduml
