@startuml

hide footbox
title Un remolque carga 3 personas en fase normal y lanaza un error

actor User

User -> Etapa **: maximo(2)
return etapa
User -> Remolque **: crear( etapa )
User -> Remolque: cargarCantidadPasajeros(3)
Remolque -> Etapa: cargarCantidadPasajeros(3)
Etapa -> NoPuedeCargarPasajeros **: signal

@enduml
